### Post
POST http://localhost:8080/article_type
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjE1NTMsImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDc5NTMsImlzcyI6Ikt1blV6VGVzdCJ9.uhqlCGTxscpXkU9s-V_fXUXjp9DYTI771uw0aJwWeD1Ugoz-Lue7RtEmVqbbry7jBA62kRwtDp5iOCy3B2bUdg

{
  "nameUz": "aaa",
  "nameRu": "bbb",
  "nameEn": "ccc",
  "orderNumber": "4"
}

### Update
PUT http://localhost:8080/article_type/updateById/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjE1NTMsImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDc5NTMsImlzcyI6Ikt1blV6VGVzdCJ9.uhqlCGTxscpXkU9s-V_fXUXjp9DYTI771uw0aJwWeD1Ugoz-Lue7RtEmVqbbry7jBA62kRwtDp5iOCy3B2bUdg

{
  "nameUz": "aaa",
  "nameRu": "bbb",
  "nameEn": "ccc"
}

### Delete
DELETE http://localhost:8080/article_type/deleteById/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjE1NTMsImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDc5NTMsImlzcyI6Ikt1blV6VGVzdCJ9.uhqlCGTxscpXkU9s-V_fXUXjp9DYTI771uw0aJwWeD1Ugoz-Lue7RtEmVqbbry7jBA62kRwtDp5iOCy3B2bUdg

### Get all by Pagination
GET http://localhost:8080/article_type/allByPagination?page=1&size=3
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjE1NTMsImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDc5NTMsImlzcyI6Ikt1blV6VGVzdCJ9.uhqlCGTxscpXkU9s-V_fXUXjp9DYTI771uw0aJwWeD1Ugoz-Lue7RtEmVqbbry7jBA62kRwtDp5iOCy3B2bUdg

### Get all by Language
GET http://localhost:8080/article_type/getByLang?language=ru




