### Post
POST http://localhost:8080/article_type
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyODk3MzAsImlkIjozMCwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzc2MTMwLCJpc3MiOiJLdW5VelRlc3QifQ.LfDMDTWnXbTQHipgdz9UIh-5LFqPRqpWnOShxDW-avU65f-E8QpFoJN4c5MyONi4OV-2ZOgyiEbCXYDItaJ86Q

{
  "nameUz": "Yangi_uz",
  "nameRu": "Yangi_ru",
  "nameEn": "Yangi_en",
  "orderNumber": "3"
}

### Update
PUT http://localhost:8080/article_type/updateById/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyODk3MzAsImlkIjozMCwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzc2MTMwLCJpc3MiOiJLdW5VelRlc3QifQ.LfDMDTWnXbTQHipgdz9UIh-5LFqPRqpWnOShxDW-avU65f-E8QpFoJN4c5MyONi4OV-2ZOgyiEbCXYDItaJ86Q

{
  "nameUz": "aaa",
  "nameRu": "bbb",
  "nameEn": "ccc"
}

### Delete
DELETE http://localhost:8080/article_type/deleteById/2
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyODk3MzAsImlkIjozMCwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzc2MTMwLCJpc3MiOiJLdW5VelRlc3QifQ.LfDMDTWnXbTQHipgdz9UIh-5LFqPRqpWnOShxDW-avU65f-E8QpFoJN4c5MyONi4OV-2ZOgyiEbCXYDItaJ86Q

### Get all by Pagination
GET http://localhost:8080/article_type/allByPagination
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyODk3MzAsImlkIjozMCwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzA3Mzc2MTMwLCJpc3MiOiJLdW5VelRlc3QifQ.LfDMDTWnXbTQHipgdz9UIh-5LFqPRqpWnOShxDW-avU65f-E8QpFoJN4c5MyONi4OV-2ZOgyiEbCXYDItaJ86Q

### Get all by Language
GET http://localhost:8080/article_type/getByLang?language=ru




