### Post
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept-Language: ru

{
  "email": "aadmin@mail.ru",
  "password": "12345"
}

###
//{
//  "email": "sanjarbeksultanov2023@gmail.com",
//  "password": "123"
//}

